name: learning_app
description: "Learning project for learners."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & icons
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2

  # Firebase core services
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_database: ^12.0.2
  firebase_storage: ^13.0.2

  # Media & player
  video_player: ^2.8.3
  chewie: ^1.7.4
  youtube_player_flutter: ^9.1.2

  # Utilities
  http: ^1.2.2
  flutter_dotenv: ^6.0.0
  flutter_inappwebview: ^6.1.5
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - .env
